version: "3.3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs:/var/log/nginx/
  nuxt:
    image: ghcr.io/zidiks/ecommerce-front/ecommerce-front:develop
    container_name: nuxt_app
    restart: always
    ports:
      - "5000:5000"
