version: '3'
services:
  hue.EC-Parf.cloud-FE:
    image: ghcr.io/zidiks/ecommerce-front/ecommerce-front:develop
    container_name: ecommerce-fe
    restart: always
    environment:
      NODE_ENV: production
    ports:
      - "80:80"
